### PR TITLE
updated important links

### PR DESCRIPTION
**Pull request by rbenson09**

### CODE REVIEW

**Comment by FelicianoTech** [comment]
@rbenson09 Did you start from the `trunk` branch before making this branch/PR? I have a hunch that not doing that is why this is failing.

**Comment by rbenson09** [comment]
@felicianotech The master branch? I started there.

**Comment by FelicianoTech** [comment]
Yeah this repo doesn't use `master` as the default anymore. It's `trunk` now. GitHub also won't use master by default anymore in new projects either. This was after a big change in text from the 2020 BLM protests.

**Comment by FelicianoTech** [comment]
You can likely fix this by running the following:

```bash
git checkout trunk
git checkout updatelinksfeb2022
git rebase trunk
git push -f
```

If you wanna do a quick video chat, let me know.

**Pull request closed without merging**
